#!/bin/sh /etc/rc.common
#Author:corecode
#Modifier:superlc

START=55
STOP=10

start()
{

#if [ $(uci get easydrcom.@login[0].boot) ] ;
#then
#	/etc/init.d/easydrcomd enable
#else
#	/etc/init.d/easydrcomd disable
#fi

if [ $(uci get easydrcom.@login[0].enable) ] ;
then
	echo [General] > /etc/config/easydrcom.test
	echo UserName=$(uci get easydrcom.@login[0].username) >> /etc/config/easydrcom.conf
	echo PassWord=$(uci get easydrcom.@login[0].password) >> /etc/config/easydrcom.conf
	echo Mode=$(uci get easydrcom.@login[0].mode) >> /etc/config/easydrcom.conf
	echo AutoOnline=$(uci get easydrcom.@login[0].autoonline) >> /etc/config/easydrcom.conf
	echo AutoRedial=$(uci get easydrcom.@login[0].autoredial) >> /etc/config/easydrcom.conf
	echo [Remote] >> /etc/config/easydrcom.test
	echo IP=$(uci get easydrcom.@login[0].ip) >> /etc/config/easydrcom.conf
	echo Port=$(uci get easydrcom.@login[0].port) >> /etc/config/easydrcom.conf
	echo UseBroadcast=$(uci get easydrcom.@login[0].usebroadcast) >> /etc/config/easydrcom.conf
	echo MAC=$(uci get easydrcom.@login[0].mac) >> /etc/config/easydrcom.conf
	echo [Local] >> /etc/config/easydrcom.test
	echo NIC=$(uci get easydrcom.@login[0].nic) >> /etc/config/easydrcom.conf
	echo EAPTimeout=$(uci get easydrcom.@login[0].eaptimeout) >> /etc/config/easydrcom.conf
	echo UDPTimeout=$(uci get easydrcom.@login[0].udptimeout) >> /etc/config/easydrcom.conf
  echo HostName=$(uci get easydrcom.@login[0].hostname) >> /etc/config/easydrcom.conf
  echo KernelVersion=$(uci get easydrcom.@login[0].kernelversion) >> /etc/config/easydrcom.conf
#	easydrcom  -r -b -c /etc/config/easydrcom.conf &
	echo "EasyDrcom Client has started."
else
	stop
fi


}

stop()
{
#	killall easydrcom
	echo "EasyDrcom Client has stoped."
}

restart()
{
stop
start
}
